# Generated by Django 4.2.11 on 2025-12-18 14:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieBilet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('denumire', models.CharField(max_length=100)),
                ('simbol', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K'), ('L', 'L'), ('M', 'M'), ('N', 'N'), ('O', 'O'), ('P', 'P'), ('Q', 'Q'), ('R', 'R'), ('S', 'S'), ('T', 'T'), ('U', 'U'), ('V', 'V'), ('W', 'W'), ('X', 'X'), ('Y', 'Y'), ('Z', 'Z')], max_length=1, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CategorieEveniment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('denumire', models.CharField(max_length=100, unique=True)),
                ('descriere', models.TextField()),
                ('culoare', models.CharField(default='#667eea', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Locatie',
            fields=[
                ('id_locatie', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nume', models.CharField(max_length=200)),
                ('descriere', models.TextField(blank=True, null=True)),
                ('capacitate', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Organizator',
            fields=[
                ('id_organizator', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nume', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Eveniment',
            fields=[
                ('id_eveniment', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nume', models.CharField(max_length=200)),
                ('descriere', models.TextField(blank=True, null=True)),
                ('data', models.DateField()),
                ('ora', models.TimeField()),
                ('durata', models.DurationField()),
                ('data_adaugare', models.DateTimeField(auto_now_add=True)),
                ('url_imagine', models.URLField(blank=True, help_text='URL către imaginea evenimentului', max_length=500, null=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evenimente', to='aplicatie_magazin_bilete.categorieeveniment')),
                ('locatie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evenimente', to='aplicatie_magazin_bilete.locatie')),
                ('organizator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evenimente', to='aplicatie_magazin_bilete.organizator')),
            ],
        ),
        migrations.CreateModel(
            name='Bilet',
            fields=[
                ('id_bilet', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pret', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sectiune', models.CharField(blank=True, max_length=10, null=True)),
                ('rand', models.PositiveIntegerField(blank=True, null=True)),
                ('loc', models.PositiveIntegerField(blank=True, null=True)),
                ('este_disponibil', models.BooleanField(default=True)),
                ('restrictie_varsta', models.PositiveIntegerField(blank=True, null=True)),
                ('este_returnabil', models.BooleanField(default=False)),
                ('categorii', models.ManyToManyField(related_name='bilete', to='aplicatie_magazin_bilete.categoriebilet')),
                ('eveniment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bilete', to='aplicatie_magazin_bilete.eveniment')),
            ],
        ),
    ]
