# Generated by Django 4.2.11 on 2026-01-15 11:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('aplicatie_magazin_bilete', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comanda',
            fields=[
                ('id_comanda', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_plasare', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'În așteptare'), ('CONFIRMED', 'Confirmată'), ('SHIPPED', 'Expediată'), ('DELIVERED', 'Livrată'), ('CANCELLED', 'Anulată')], default='PENDING', max_length=20)),
                ('metoda_plata', models.CharField(choices=[('CARD', 'Card bancar'), ('CASH', 'Numerar'), ('TRANSFER', 'Transfer bancar')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Utilizator',
            fields=[
                ('id_utilizator', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('parola', models.CharField(max_length=255)),
                ('nume', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('tara', models.CharField(max_length=100)),
                ('cnp', models.CharField(max_length=13, unique=True)),
                ('telefon', models.CharField(max_length=20)),
                ('poza', models.URLField(blank=True, max_length=500, null=True)),
                ('tip_cont', models.CharField(choices=[('STANDARD', 'Standard'), ('PREMIUM', 'Premium'), ('ADMIN', 'Administrator')], default='STANDARD', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id_voucher', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('procent_reducere', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('data_expirare', models.DateTimeField()),
                ('comanda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vouchere', to='aplicatie_magazin_bilete.comanda')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id_review', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nota', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('mesaj', models.TextField()),
                ('data_creare', models.DateTimeField(auto_now_add=True)),
                ('eveniment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='aplicatie_magazin_bilete.eveniment')),
                ('utilizator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='aplicatie_magazin_bilete.utilizator')),
            ],
        ),
        migrations.AddField(
            model_name='comanda',
            name='utilizator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comenzi', to='aplicatie_magazin_bilete.utilizator'),
        ),
    ]
