# Generated by Django 4.2.11 on 2026-01-15 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplicatie_magazin_bilete', '0002_comanda_utilizator_voucher_review_comanda_utilizator'),
    ]

    operations = [
        migrations.AddField(
            model_name='bilet',
            name='comanda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bilete', to='aplicatie_magazin_bilete.comanda'),
        ),
        migrations.AlterField(
            model_name='comanda',
            name='status',
            field=models.CharField(choices=[('PENDING', 'În așteptare'), ('CONFIRMED', 'Confirmată'), ('DELIVERED', 'Livrată'), ('CANCELLED', 'Anulată')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='review',
            name='nota',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='utilizator',
            name='cnp',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='utilizator',
            name='tara',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='utilizator',
            name='telefon',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='utilizator',
            name='tip_cont',
            field=models.CharField(choices=[('BRONZE', 'Bronze'), ('SILVER', 'Silver'), ('GOLD', 'Gold')], default='BRONZE', max_length=20),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='procent_reducere',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
